server:
  port: 8189
  address: 0.0.0.0
  tomcat:
    max-http-form-post-size: 100MB

shenyu:
  namespace: 649330b6-c2d7-4edc-be8e-8a54df9eb385
  register:
    registerType: http
    serverLists: http://localhost:9095
    props:
      username: admin
      password: 123456
  client:
    http:
      props:
        contextPath: /http
        appName: http
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: info
    org.springframework.boot: info
    org.apache.ibatis: info
    org.apache.shenyu.test.bonuspoint: info
    org.apache.shenyu.test.lottery: debug
    org.apache.shenyu.test: debug
